services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
  postgres-products:
    image: postgres:latest
    ports:
      - "34567:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
  postgres-tariffs:
    image: postgres:latest
    ports:
      - "34568:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: tariffs_db
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_BROKERS: "kafka:29092"
    depends_on:
      - kafka
  redpanda-console-remote:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-ui-remote
    restart: unless-stopped
    ports:
      - "8017:8080"  # выставляем на другой порт, например 8082
    environment:
      KAFKA_BROKERS: #host:8080
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM: SCRAM-SHA-256
      KAFKA_SASL_USERNAME: #login
      KAFKA_SASL_PASSWORD: #password
