spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: warehouse-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:34567/mydatabase
    driverClassName: org.postgresql.Driver
    username: myuser
    password: mypassword

server:
  port: 6790
