spring:
  security:
    user:
      name: user
      password: qwerty
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:34567/mydatabase
    driverClassName: org.postgresql.Driver
    username: myuser
    password: mypassword
    jpa:
      hibernate:
        ddl-auto: update

server:
  port: 6789

warehouse-service:
  base-url: http://localhost:6790

resilience4j:
  circuitbreaker:
    instances:
      warehouse:
        slidingWindowSize: 5
        failureRateThreshold: 50
  retry:
    instances:
      warehouse:
        maxAttempts: 3
        waitDuration: 500ms
